name: chat_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  image_picker: ^1.0.1
  intl: ^0.20.1
  provider: ^6.0.5

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
